---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Remove default debian configuration for fail2ban
  file:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    state: absent

- name: Configure fail2ban
  template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
